version: 2.1

jobs:
  test:
    docker:
      - image: januszewskimar/shop-safe:latest
    steps:
      - checkout
      - run: npm ci
      - run: grunt test

workflows:
  test:
    jobs:
      - test

